development:
  adapter: mysql2
  database: blog_dev
  pool: 5
  username: root
  password:
  host: localhost
  reconnect: true

test:
  adapter: mysql2
  database: blog_test
  pool: 5
  username: root
  password:
  host: localhost
  reconnect: true
